Repository gdsc-konkuk/24-25-proj-PlanPal-Client, pull requests merged in 2025-05, with the labels that each got.

#24 Feature/chat
  public/placeholder.svg
  src/app/(auth)/dashboard/invite/page.tsx
  src/app/(auth)/dashboard/page.tsx
  src/app/modules/chat/api/chat-room.ts
  src/app/modules/chat/create-chat-modal.tsx
  src/app/modules/chat/utils/format-date.ts
  src/hooks/use-api.ts
Labels: enhancement, feature

#29 Integrate WebSocket-based real-time chat and invitation flow enhancements
  cloudbuild.yaml
  src/app/(auth)/dashboard/invite/page.tsx
  src/app/(auth)/dashboard/layout.tsx
  src/app/(auth)/dashboard/page.tsx
  src/app/(auth)/layout.tsx
  src/app/explore/page.tsx
  src/app/layout.tsx
  src/app/modules/auth/api/logout.ts
  src/app/modules/chat/api/chat-room.ts
  src/app/modules/chat/create-chat-modal.tsx
  src/app/modules/chat/initializer/websocket-initializer.tsx
  src/app/modules/chat/store/websocket-store.ts
  src/app/modules/chat/types/index.ts
  src/app/modules/chat/ui/chat.tsx
  src/app/modules/chat/ui/components/chat-header.tsx
  src/app/modules/chat/ui/left-panel.tsx
  src/app/modules/chat/ui/middle-panel.tsx
  src/app/modules/chat/ui/right-panel.tsx
  src/components/initializer/auth-initializer.tsx
  src/hooks/use-api.ts
  src/store/auth-store.ts
Labels: feature

#30 Unify chat message structure with WebSocket-driven real-time updates
  src/app/modules/chat/store/websocket-store.ts
  src/app/modules/chat/types/index.ts
  src/app/modules/chat/ui/chat.tsx
  src/app/modules/chat/ui/components/chat-message-card.tsx
  src/app/modules/chat/ui/components/chat-message.tsx
  src/app/modules/chat/ui/right-panel.tsx
Labels: feature

#32 Fix environment variable
  cloudbuild.yaml
Labels: bug

#36 Refresh pins on WebSocket trigger and ensure unique place dialogs
  src/app/modules/chat/store/websocket-store.ts
  src/app/modules/chat/ui/middle-panel.tsx
  src/app/modules/map/store/liked-place-store.ts
  src/app/modules/map/ui/components/google-map.tsx
Labels: feature, refactor

#37 Update sendMessage type to include 'aiRequest'
  src/app/modules/chat/store/websocket-store.ts
  src/app/modules/chat/ui/chat.tsx
  src/app/modules/chat/ui/components/chat-message-card.tsx
Labels: bug

#40 feat(map-overlay): add requestRefreshMap integration for map updates
  src/app/modules/chat/store/websocket-store.ts
  src/app/modules/map/ui/components/map-overlay.tsx
Labels: feature
